### ISSUE TITLE
March 2022 pages dataset grew by ~2x

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/data-pipeline#42]
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/1120896/165772433-af65370e-d2b4-46e8-b147-3c0921d32297.png">

[BQ meta dashboard](https://datastudio.google.com/u/0/reporting/1jh_ScPlCIbSYTf2r2Y6EftqmX9SQy4Gn/page/YfRe)

The number of rows in the pages tables has stayed relatively consistent, but in March the size of the desktop and mobile tables grew by about 2x.

Investigate what caused the change and update the pipeline to reduce the size going forward.

**Comment by tunetheweb** [comment]
Did we ever look into this @rviscomi / @pmeenan ? It’s the same again this month.

**Comment by rviscomi** [comment]
I haven't looked into this yet

**Comment by pmeenan** [comment]
Looks like the axe audit data somehow bled through (and it is huge). We should be running the tests with axe=0 which should turn it off but clearly it didn't starting in March.

I spot-checked a few of the raw HARs for the crawl that just started and the axe data isn't included so it should be fixed in the May crawl.

My guess is the WPT server-side code stopped passing the axe option through as a test option when passed through the API. Since we're no longer using the web UI to manage the jobs, the option is flowing through correctly again.
