### ISSUE TITLE
Summary pipeline: TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/data-pipeline#50]
GCP error: https://console.cloud.google.com/errors/detail/COjus87xie3gaA;time=PT1H?project=httparchive

```
 Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/modules/transformation.py", line 124, in process
    page, requests = self.generate_pages(file_name, data)
  File "/usr/local/lib/python3.8/site-packages/modules/transformation.py", line 161, in generate_pages
    entries, first_url, first_html_url = ImportHarJson.import_entries(
TypeError: cannot unpack non-iterable NoneType object
```

Looks like `import_entries` returns None sometimes, which can't be unpacked into `entries, first_url, first_html_url`.

**Comment by giancarloaf** [comment]
Investigating. 

Likely caused by the return in this block of `modules.transformation.ImportHarJson.import_entries()`
https://github.com/HTTPArchive/data-pipeline/blob/c51fa1ea354f29a9d3b992c2f7924919216b8dd6/modules/transformation.py#L359-L364

**Comment by rviscomi** [comment]
Agreed.

What will happen to the pages that encounter this error, will they retry indefinitely?

**Comment by giancarloaf** [comment]
Since these are failing in the HAR processing step (not the read or write steps), it should not retry at all and there shouldn't be a risk of holding up the pipeline. These will need to be reprocessed once the code has been updated with a fix.

Examples are easy to pick out of the logs, so we can test with them. The error rate is very low as well - currently about 90 out of 2.4 million HAR files processed have failed to parse with this error.

**Comment by rviscomi** [comment]
0.00375% sounds low enough to me that we probably don't need to worry about rerunning them for the May crawl 😁 

But it would still be good to fix for the next crawls to avoid repeating the error.
